config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :gitcasts, only: :show

  resource :feed, only: :show, defaults: { format: :atom }, controller: :feed
end

app/models/gitcast.rb
class Gitcast < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }

  validates_presence_of :name, :src, :episode_number, :length
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feed_controller.rb
class FeedController < ::ApplicationController
  def show
    @gitcasts = Gitcast.all

    respond_to do |format|
      format.atom { render layout: false }
      format.rss { redirect_to feed_path(format: :atom), status: :moved_permanently }
    end
  end
end

app/controllers/gitcasts_controller.rb
class GitcastsController < ::ApplicationController
  def show
    @gitcast = Gitcast.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ::ApplicationController
  def home
    @gitcasts = Gitcast.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/gitcasts/show.slim
.episode-video
  h1.episode-name = @gitcast.name

  iframe width="854" height="510" src="#{@gitcast.src}" frameborder="0" allowfullscreen

app/views/layouts/application.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="ROBOTS" content="NOODP"
    title = title
    link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Lato:300italic,400italic' rel='stylesheet' type='text/css'
    = stylesheet_link_tag :application, media: 'all'
    link rel="icon" type="image/png" href="#{image_path 'favicon-32x32.png'}" sizes="32x32"
    link rel="icon" type="image/png" href="#{image_path 'favicon-16x16.png'}" sizes="16x16"
    = auto_discovery_link_tag :atom, feed_path
    = auto_discovery_link_tag :rss, feed_path(format: :rss)
    - if Rails.env.production?
      = render 'shared/google_analytics'
    = csrf_meta_tags
  body
    header
      = link_to root_path
        h1.title
          span.title-first-word git
          span.title-last-word casts

      span.inspirational-sentence Providing you your daily dosage of git

    .container
      = render 'flashes'

      .main-content
        = yield

      .donation
        = render 'shared/donation'

    footer
      p.credits
        | Brought to you by&nbsp;
        = link_to "Luís Zamith", "http://blog.zamith.pt/"

    = render 'javascript'

app/views/pages/home.slim
section.episodes
  ul
    - @gitcasts.each do |gitcast|
      li.episode
        .episode-number = gitcast.episode_number
        .episode-info
          = link_to gitcast.name, gitcast_path(gitcast), class: "episode-name"
          .episode-extra-info = l(gitcast.created_at, format: :date) + " - #{gitcast.length}"

app/views/shared/_donation.slim
p Gitcasts is free, that means you don't have to pay for any of the content. If you want to help keep it going, please do it here:
form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"
  input type="hidden" name="cmd" value="_s-xclick"
  input type="hidden" name="hosted_button_id" value="45FV9BADGKBQA"
  input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"
  img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"

app/views/shared/_google_analytics.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58207299-1', 'auto');
  ga('send', 'pageview');